/// Part 1: Basic Methods

### Request via GET
GET http://localhost:8080/v1/part1

### Request via PUT
PUT http://localhost:8080/v1/part1

### Request via POST
POST http://localhost:8080/v1/part1

### Request via DELETE
DELETE http://localhost:8080/v1/part1

/// Part 2: Content-Type

### Request any content from server
GET http://localhost:8080/v1/part2
Content-Type: *

### Request html content from server
GET http://localhost:8080/v1/part2
Content-Type: text/html

### Request json content from server
GET http://localhost:8080/v1/part2
Content-Type: application/json

/// Part 3: Headers

### Request json content from server
GET http://localhost:8080/v1/part3
User-Agent: iPhone

### Request any content from server
POST http://localhost:8080/v1/part3
Custom-Header: CustomHeader

/// Part 4: Request Variables

### Provide name "Bob"
GET http://localhost:8080/v1/part4?name=Bob

// Part 5: Path Variable
### Provide name "Bob" and region "us"
GET http://localhost:8080/v1/en-US/part5?name=Bob

### Provide name "Bob" and region "de"
GET http://localhost:8080/v1/de-DE/part5?name=Bob

/// Part 6: Response Status

### Provide no name
GET http://localhost:8080/v1/part6

### Provide name "Matt"
GET http://localhost:8080/v1/part6?name=Matt

### Provide name "Lucy"
GET http://localhost:8080/v1/part6?name=Lucy

/// Final Practice
### Say Hello to Matt
GET http://localhost:8080/v1/gea/my-greeting-endpoint?name=Matt&surname=Damon

### Say Hello to Bob Dylan without Age
GET http://localhost:8080/v1/gea/my-greeting-endpoint?name=Bob&surname=Dylan

### Say Hello to Bob Dylan with Age
GET http://localhost:8080/v1/gea/my-greeting-endpoint?name=Bob&surname=Dylan&age=82

